version: 2
jobs:
  build:
    docker:
      - image: node:11.15.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Git configs"
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test

      - run: yarn build

      - run: yarn deploy
